swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Account Module
      summary: User Account API
      description: account recovery
      parameters:
        - in: path
          name: id
          description: Account Access
          required: true
          type: string
      responses:
        "200":
          description: Account access successful
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "404":
          description: An error occured
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Transaction Api
      description: API to retrieve transactions
      parameters:
        - in: path
          name: accountId
          description: Recovery Of Identifier
          required: true
          type: string
      responses:
        "200":
          description: Access to successful transaction
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "403":
          description: None Authorized
        "404":
          description: An error occured
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transaction Module
      summary: User Transaction Api
      description: API to retrieve transactions
      parameters:
        - in: path
          name: accountId
          description: Recovery Of Identifier
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction Access
          required: true
          type: string
      responses:
        "200":
          description: Access to successful transaction
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "403":
          description: None Authorized
        "404":
          description: An error occured
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: Update Transaction Category and Note
      description: API for updating the category and note of a specific transaction
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: Id account
        - in: path
          name: transactionId
          required: true
          type: string
          description: Id transaction
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Added transaction successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid fields or request
        "404":
          description: An error occured
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Accounts:
    type: object
    properties:
      id:
        type: string
        description: Identifiant du compte utilisateur
      name:
        type: string
        description: Nom de l'utilisateur
      email:
        type: string
        format: email
        description: Adresse e-mail de l'utilisateur
      balance:
        type: number
        description: Solde du compte
    required:
      - id
      - name
      - email
      - balance

  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant de la transaction
      accountId:
        type: string
        description: Identifiant du compte associé à la transaction
      amount:
        type: number
        description: Montant de la transaction
      date:
        type: string
        format: date-time
        description: Date et heure de la transaction
      description:
        type: string
        description: Description de la transaction
    required:
      - id
      - accountId
      - amount
      - date

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Nouvelle catégorie de la transaction
      note:
        type: string
        description: Nouvelle note associée à la transaction
    required:
      - category
      - note
